scripts:
  - flutter pub get
  - flutter build ios --release --no-codesign

  # DEBUG: lihat isi folder
  - echo "ISI FOLDER:"
  - ls -R build/ios

  # paksa zip semua isi build ios
  - cd build/ios
  - zip -r ios_build.zip .

artifacts:
  - build/ios/ios_build.zip
