workflows:
  ios-release:
    name: iOS Build No Sign

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Prepare iOS
        script: flutter build ios --config-only

      - name: Build iOS without signing
        script: |
          cd ios
          pod install

          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" build

      - name: Create IPA
        script: |
          mkdir -p build_output/Payload
          cp -r build/ios/iphoneos/Runner.app build_output/Payload/
          cd build_output
          zip -r app.ipa Payload

    artifacts:
      - build_output/app.ipa