workflows:
  ios-release:
    name: iOS Build (No Sign)

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get packages
        script: flutter pub get

      # 🔥 FIX: pakai simulator (ANTI GAGAL)
      - name: Build iOS Simulator
        script: flutter build ios --simulator

      # 🔥 packaging
      - name: Create ZIP
        script: |
          mkdir -p build_output
          cp -r build/ios/iphonesimulator/*.app build_output/
          cd build_output
          zip -r app.zip .

    artifacts:
      - build_output/app.zip
